# Extract

In [ ]:
import pandas as pd
from datetime import datetime

In [ ]:
# Create Log File
def log(message):
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    with open("logfile.txt", "a") as file:
        file.write(f"[{timestamp}] {message}\n")

In [ ]:

def extract_csvFile(file_path):
    try:
        df = pd.read_csv(file_path, encoding="latin1")
        log("Data extracted successfully")
        print(f"Data extracted successfully: {df.shape}")
        return df

    except Exception as e:
        log(f"Error has been detected: {e}")
        print(f"Error has been detected: {e}")
        return None

In [ ]:
fileName = 'Dataset/data.csv'
extract_csvFile(fileName)

Data extracted successfully: (541909, 8)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/2011 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/2011 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/2011 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/2011 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/2011 12:50,4.95,12680.0,France

# DATA QUALITY CHECK

In [ ]:
# Finding the missing and duplicate records
def data_quality_report(df):

    print("Shape:", df.shape)

    print("\nData Types:")
    print(df.dtypes)

    print("\nMissing Values:")
    print(df.isnull().sum())

    print("\nDuplicate Rows:")
    print(df.duplicated().sum())

In [ ]:
E_CommerceDF = extract_csvFile(fileName)
log("Data Checked Successfully")
data_quality_report(E_CommerceDF)

Data extracted successfully: (541909, 8)
Shape: (541909, 8)

Data Types:
InvoiceNo       object
StockCode       object
Description     object
Quantity         int64
InvoiceDate     object
UnitPrice      float64
CustomerID     float64
Country         object
dtype: object

Missing Values:
InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

Duplicate Rows:
5268

# TRANSFORM

In [ ]:
# Convert and Change the date to date time format
try:
    E_CommerceDF["InvoiceDate"] = pd.to_datetime(
        E_CommerceDF["InvoiceDate"],
        errors="coerce"
    )
    log("InvoiceDate Transformed Successfully ")
except Exception as e:
    log(f"An Error has beed detected {e}")

In [ ]:
# Split InvoiceDate into different format 
try:
    E_CommerceDF["Year"] = E_CommerceDF["InvoiceDate"].dt.year
    E_CommerceDF["Month"] = E_CommerceDF["InvoiceDate"].dt.month
    E_CommerceDF["MonthName"] = E_CommerceDF["InvoiceDate"].dt.month_name()
    E_CommerceDF["Weekday"] = E_CommerceDF["InvoiceDate"].dt.day_name()
    log("InvoiceDate Splited Successfully ")
except Exception as e:
    log(f"An Error has beed detected {e}")

In [ ]:
# Calculate Total Amount
try:
    E_CommerceDF['TotalAmount'] = E_CommerceDF['Quantity'] * E_CommerceDF['UnitPrice']
    log("TotalAmount Calculated Successfully ")
except Exception as e:
    log(f"An Error has beed detected {e}")

In [ ]:
# Removing the missing values
try:
    E_CommerceDF.dropna()
    log("Missing Values Removed Successfully ")
except Exception as e:
    log(f"An Error has beed detected {e}")

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Year,Month,MonthName,Weekday,Quarter,TotalAmount
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,2010,12,December,Wednesday,4,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,2010,12,December,Wednesday,4,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,2010,12,December,Wednesday,4,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,2010,12,December,Wednesday,4,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,2010,12,December,Wednesday,4,20.34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,France,2011,12,December,Friday,4,10.20
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,France,2011,12,December,Friday,4,12.60
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,France,2011,12,December,Friday,4,16.60
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,France,2011,12,December,Friday,4,16.60
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680.0,France,2011,12,December,Friday,4,14.85

# ANALYZE

## Q1.Which countries have the most orders?

In [ ]:
orders_by_country = (
    E_CommerceDF.groupby("Country")[
        "InvoiceNo"].nunique().sort_values(ascending=False)
)
try:
    orders_by_country
    log("Most orders by countries Analyzed Successfully ")
except Exception as e:
    log(f"An Error has beed detected {e}")

## Q2.Which months have the highest order volume?

In [ ]:
Highest_Orders_In_Months= (
    E_CommerceDF.groupby("Month")["InvoiceNo"]
      .nunique()
      .sort_values(ascending=False)
)
try:
    Highest_Orders_In_Months
    log("Highest orders by months Analyzed Successfully ")
except Exception as e:
    log(f"An Error has beed detected {e}")

Month
11    3462
12    3040
10    2637
9     2327
5     2162
6     2012
3     1983
7     1927
4     1744
8     1737
1     1476
2     1393
Name: InvoiceNo, dtype: int64

## Q3.Which weekdays are busiest?

In [ ]:
Busiest_Days = (
    E_CommerceDF.groupby("Weekday")["InvoiceNo"]
      .nunique()
      .sort_values(ascending=False)
) 

try:
    Busiest_Days
    log("Busiest Days Analyzed Successfully ")
except Exception as e:
    log(f"An Error has beed detected {e}")

Weekday
Thursday     5660
Wednesday    4815
Tuesday      4722
Friday       4184
Monday       4138
Sunday       2381
Name: InvoiceNo, dtype: int64

## Q4.Which products generate the highest sales?

In [ ]:
Highest_Product_sales = (
    E_CommerceDF.groupby("Description")["TotalAmount"]
    .sum()
    .sort_values(ascending=False)
    )

try:
    Highest_Product_sales
    log("Highest Products Sales Analyzed Successfully ")
except Exception as e:
    log(f"An Error has beed detected {e}")

Description
DOTCOM POSTAGE                        206245.480
REGENCY CAKESTAND 3 TIER              164762.190
WHITE HANGING HEART T-LIGHT HOLDER     99668.470
PARTY BUNTING                          98302.980
JUMBO BAG RED RETROSPOT                92356.030
                                         ...
Bank Charges                           -7175.639
CRUK Commission                        -7933.430
Adjust bad debt                       -11062.060
Manual                                -68671.640
AMAZON FEE                           -221520.500
Name: TotalAmount, Length: 4223, dtype: float64

## Q5.Which countries generate the highest revenue?

In [ ]:
Highest_Country_Revenue = (
    E_CommerceDF.groupby("Country")["TotalAmount"].sum()
    .sort_values(ascending=False)
)
 
try:
    Highest_Country_Revenue
    log("Highest Country Revenue Analyzed Successfully ")
except Exception as e:
    log(f"An Error has beed detected {e}")

Country
United Kingdom          8187806.364
Netherlands              284661.540
EIRE                     263276.820
Germany                  221698.210
France                   197403.900
Australia                137077.270
Switzerland               56385.350
Spain                     54774.580
Belgium                   40910.960
Sweden                    36595.910
Japan                     35340.620
Norway                    35163.460
Portugal                  29367.020
Finland                   22326.740
Channel Islands           20086.290
Denmark                   18768.140
Italy                     16890.510
Cyprus                    12946.290
Austria                   10154.320
Hong Kong                 10117.040
Singapore                  9120.390
Israel                     7907.820
Poland                     7213.140
Unspecified                4749.790
Greece                     4710.520
Iceland                    4310.000
Canada                     3666.380
Malta                      2505.470
United Arab Emirates       1902.280
USA                        1730.920
Lebanon                    1693.880
Lithuania                  1661.060
European Community         1291.750
Brazil                     1143.600
RSA                        1002.310
Czech Republic              707.720
Bahrain                     548.400
Saudi Arabia                131.170
Name: TotalAmount, dtype: float64

## LOAD

In [ ]:
# save the cleaned data

try:
    E_CommerceDF.to_csv(
    "output/cleaned_orders.csv",
    index=False)
    log("Cleaned Data Loaded Successfully ")
except Exception as e:
    log(f"An Error has beed detected {e}")

In [ ]:
# Aggregated Summary Table (The Highest Countries Sales)

try:
    Highest_Country_Revenue.to_csv(
        "output/summary_country_sales.csv" )
    log("The Highest Countries Sales Loaded Successfully ")
except Exception as e:
    log(f"An Error has beed detected {e}")